version: '3.9'
name: wallabag
# wallabag stack

# wallabag
#
# Page: https://wallabag.org/
# Code: https://github.com/wallabag
# Dckr: https://hub.docker.com/r/wallabag/wallabag
# Cmps: https://github.com/wallabag/docker#docker-compose
#
# wallabag is a self hostable application for saving web pages: Save and
# classify articles. Read them later. Freely.

services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: mariadb:${WALLABAG_MARIADB_TAG:-11}
    environment:
      - MYSQL_ROOT_PASSWORD
      - MARIADB_MYSQL_LOCALHOST_USER
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 20s
      timeout: 3s

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:${WALLABAG_REDIS_TAG:-7-alpine}
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

  wallabag:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: wallabag/wallabag:${WALLABAG_TAG:-latest}
    depends_on:
      - db
      - redis
    env_file: stack.env
    networks:
      - default
      - proxy
      - smtp
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/assets:/var/www/wallabag/web/assets/images
      - /etc/${COMPOSE_PROJECT_NAME}:/var/www/wallabag/app/config
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  default:
  proxy:
    external: true
  smtp:
    external: true
