version: '3.9'
name: ntfy
# ntfy stack

# ntfy stack
#
# Page: https://ntfy.sh/
# Code: https://github.com/binwiederhier/ntfy
# Dckr: https://hub.docker.com/r/binwiederhier/ntfy
# Cmps: https://docs.ntfy.sh/install/#docker
#
# ntfy (pronounced "notify") is a simple HTTP-based pub-sub notification
# service. With ntfy, you can send notifications to your phone or desktop via
# scripts from any computer, without having to sign up or pay any fees. If you'd
# like to run your own instance of the service, you can easily do so since ntfy
# is open source.

services:

  ntfy:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: binwiederhier/ntfy:${NTFY_TAG:-latest}
    command:
      - serve
    restart: unless-stopped
    networks:
      - proxy
      - smtp
      - prometheus
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/etc/ntfy
      - /srv/${COMPOSE_PROJECT_NAME}:/srv/ntfy
      - /var/log/${COMPOSE_PROJECT_NAME}:/var/log/ntfy
      - /var/${COMPOSE_PROJECT_NAME}:/var/ntfy
    healthcheck:
        test: "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"
        start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  smtp:
    external: true
  prometheus:
    external: true
