version: '3.9'
name: homepage
# homepage stack

# homepage
#
# Page: https://gethomepage.dev/latest/
# Repo: https://github.com/gethomepage/homepage
# Dckr: https://github.com/gethomepage/homepage/pkgs/container/homepage
# Cmps: https://gethomepage.dev/latest/installation/docker/
#
# A modern, fully static, fast, secure fully proxied, highly customizable
# application dashboard with integrations for over 100 services and translations
# into multiple languages. Easily configured via YAML files or through docker
# label discovery.

services:

  homepage:
    container_name: ${COMPOSE_PROJECT_NAME}
    hostname: ${COMPOSE_PROJECT_NAME}
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_TAG:-latest}
    networks:
      - proxy
      - exposed
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/app/config
      - /var/log/${COMPOSE_PROJECT_NAME}:/app/log
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${NETWORK_DOMAIN:?Netowrk domain is not defined}`) || Host(`${COMPOSE_PROJECT_NAME}.${NETWORK_DOMAIN}`) || Host(`${COMPOSE_PROJECT_NAME}.${MACHINE_DOMAIN:?Machine domain is not defined}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
  exposed:
    external: true
