version: '3.9'
name: homebox
# Homebox stack

# Homebox
#
# Page: https://hay-kot.github.io/homebox/
# Repo: https://github.com/hay-kot/homebox
# Dckr: https://github.com/hay-kot/homebox/pkgs/container/homebox
# Cmps: https://hay-kot.github.io/homebox/quick-start/
#
# Homebox is the inventory and organization system built for the Home User! With
# a focus on simplicity and ease of use, Homebox is the perfect solution for
# your home inventory, organization, and management needs.

services:

  homebox:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ghcr.io/hay-kot/homebox:${HOMEBOX_TAG:-latest}
    restart: unless-stopped
    networks:
      - proxy
      - smtp
    env_file: stack.env
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${SHORT_DOMAIN:?Short FQDN missing}`) || Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTHENTICATION:?No authentication middleware provided}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=7745"

networks:
  proxy:
    external: true
  smtp:
    external: true
