version: '3.9'
name: netdata
# Netdata stack

# Netdata
#
# Page: https://www.netdata.cloud/
# Repo: https://github.com/netdata/netdata
# Dckr: https://hub.docker.com/r/netdata/netdata
# Cmps: https://learn.netdata.cloud/docs/netdata-agent/installation/docker#docker-composeyml
#
# Netdata collects metrics per second and presents them in beautiful
# low-latency dashboards. It is designed to run on all of your physical and
# virtual servers, cloud deployments, Kubernetes clusters, and edge/IoT devices,
# to monitor your systems, containers, and applications.

services:

  agent:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: netdata/netdata:${NETDATA_VERSION:-stable}
    restart: unless-stopped
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/etc/netdata
      - /srv/${COMPOSE_PROJECT_NAME}:/var/lib/netdata
      - /tmp/${COMPOSE_PROJECT_NAME}:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro # https://learn.netdata.cloud/docs/installing/docker#with-systemd-units-monitoring
      - /etc/hostname:/host/etc/hostname:ro # https://learn.netdata.cloud/docs/installing/docker#change-the-default-hostname
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${NETWORK_DOMAIN:?Netowrk domain is not defined}`) || Host(`${COMPOSE_PROJECT_NAME}.${MACHINE_DOMAIN:?Machine domain is not defined}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=19999"

volumes:
  netdatalib:
  netdatacache:
